language: python
cache:
  pip: true
  directories:
    - node_modules
    - bower_components
python:
  - "2.7"
  - "3.4"
before_install:
  - nvm install 4.2
install:
  - make requirements-dev npm-install
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
